{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_milliseconds_total[1m])",
     "legendFormat": "Request Latency"
    },
    {
     "expr": "rate(pizza_request_duration_ms_milliseconds_total[1m])",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  },
  {
   "title": "HTTP requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{method=\"all\"}[1m]) * 60",
     "legendFormat": "All Requests"
    },
    {
     "expr": "rate(http_requests_total{method=\"GET\"}[1m]) * 60",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(http_requests_total{method=\"DELETE\"}[1m]) * 60",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(http_requests_total{method=\"POST\"}[1m]) * 60",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(http_requests_total{method=\"PUT\"}[1m]) * 60",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "Revenue/minute",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_usd_total[1m])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{result=\"SUCCESS\"}[1m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(pizzas_sold_total{result=\"FAILURE\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "rate(auth_attempts_total{result=\"Failure\"}[1m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(auth_attempts_total{result=\"Success\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory_usuage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 8, "y": 20 },
   "targets": [
    { "expr": "active_users_ratio", "legendFormat": "Active Users" }
   ]
  }
 ]
}